export const CRM_ROUTES = {
  adminDashboard: "/admin/dashboard",
  adminLeads: "/admin/leads",
  adminLeadDetail: (id: string) => `/admin/leads/${id}`,
  adminFollowUps: "/admin/follow-ups",
  adminCustomers: "/admin/customers",
  adminCustomerDetail: (id: string) => `/admin/customers/${id}`,
  adminEmployees: "/admin/employees",
  adminSurveys: "/admin/surveys",
  adminSurveyDetail: (id: string) => `/admin/surveys/${id}`,
  adminQuotations: "/admin/quotations",
  adminQuotationDetail: (id: string) => `/admin/quotations/${id}`,
  adminProjects: "/admin/projects",
  adminProjectDetail: (id: string) => `/admin/projects/${id}`,
  adminMaterials: "/admin/materials",
  adminProducts: "/admin/products",
  adminMarketingLeads: "/admin/marketing-leads",
  adminReports: "/admin/reports",
  adminSettings: "/admin/settings",

  employeeDashboard: "/employee/dashboard",
  employeeLeads: "/employee/leads",
  employeeLeadDetail: (id: string) => `/employee/leads/${id}`,
  employeeFollowUps: "/employee/follow-ups",
  employeeSurveys: "/employee/surveys",
  employeeSurveyDetail: (id: string) => `/employee/surveys/${id}`,
  employeeQuotations: "/employee/quotations",
  employeeQuotationDetail: (id: string) => `/employee/quotations/${id}`,
  employeeProjects: "/employee/projects",
  employeeProjectDetail: (id: string) => `/employee/projects/${id}`,
  employeeSettings: "/employee/settings",

  partnerDashboard: "/partner/dashboard",
  partnerLeads: "/partner/leads",
  partnerLeadDetail: (id: string) => `/partner/leads/${id}`,
  partnerProjects: "/partner/projects",
  partnerCommissions: "/partner/commissions",
  partnerProfile: "/partner/profile",

  adminPartners: "/admin/partners",
  adminPartnerNew: "/admin/partners/new",
  adminPartnerDetail: (id: string) => `/admin/partners/${id}`,
  adminCommissions: "/admin/commissions",
} as const;
